default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: elearning_app_development


test:
  <<: *default
  database: elearning_app_test


production:
  <<: *default
  database: elearning_app_production
  username: elearning_app
  password: <%= ENV["ELEARNING_APP_DATABASE_PASSWORD"] %>
